# Generated by Django 3.2.4 on 2021-11-28 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_auto_20211128_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-created']},
        ),
    ]
